name: checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04

    services:
      docker:
        image: docker:19.03.12-dind  # Docker in Docker image
        options: --privileged         # Grant necessary privileges for DinD
        ports:
          - 2375:2375                # Expose Docker port

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Correct action repository for Buildx
        with:
          version: '20.10.16'  # Set Docker version
          docker-compose-version: '1.29.2'  # Set Docker Compose version

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Verify Docker and Docker Compose
      - name: Verify Docker and Docker Compose
        run: |
          docker --version
          docker-compose --version

      - name: Build and run tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
