name: checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04

    services:
      docker:
        image: docker:19.03.12-dind  # This will start Docker in Docker
        options: --privileged         # Required for DinD to work
        ports:
          - 2375:2375                # Exposing the Docker daemon port

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          version: '20.10.16'  # Use the latest supported Docker version
          docker-compose-version: '1.29.2'  # Ensure Docker Compose is available

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Verifying Docker and Docker Compose
      - name: Verify Docker and Docker Compose
        run: |
          docker --version
          docker-compose --version

      - name: Build and run tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
