name: checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04

    services:
      docker:
        image: docker:19.03.12-dind  # Docker in Docker image
        options: --privileged         # Necessary for DinD
        ports:
          - 2375:2375                # Expose Docker port
        env:
          DOCKER_TLS_CERTDIR: ""      # Disable TLS for Docker daemon to avoid errors with DinD

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'  # Use the latest version of Buildx available

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Docker and Docker Compose
        run: |
          docker --version
          docker-compose --version

      - name: Set Docker Host Environment
        run: echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

      - name: Build and run tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
