name: checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1  # Use this action to set up Docker
        with:
          version: 20.10.7   # Use a stable Docker version
          buildx: true       # Enable Buildx for builds

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Docker and Docker Compose
        run: |
          docker --version
          docker-compose --version

      - name: Build and run tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
